from django.conf.urls.defaults import *

urlpatterns = patterns('apps.sequences.views',
    (r'^$', 'index'),
    (r'^songs/$', 'song_index'),
    (r'^songs/(?P<id>\d+)/$', 'edit_song'),
    (r'^songs/(?P<id>\d+)/delete/$', 'delete_song'),
    (r'^stats_index/$', 'index_with_stats'),
    (r'^notes/$', 'notes_summary'),
    (r'^category_use/$', 'category_use'),
    (r'^omissions/table/$', 'omissions_summary', {'table':True}),
    (r'^omissions/$', 'omissions_summary'),
    (r'^view_all/$', 'view_sequences'),
    (r'^(?P<id>\d+)/delete/$', 'delete_sequence'),
    (r'^(?P<id>\d+)/$', 'edit_sequence'),
    (r'^(?P<id>\d+)/annotate/$', 'annotate_sequence'),
    url(r'^(\d+)/start_reannotate/$', 'reannotate_sequence', { 'new' : True },
            name="start-reannotate"),
    url(r'^(\d+)/reannotate/$', 'reannotate_sequence', { 'new' : False },
            name="reannotate"),
    (r'^add/$', 'add_sequence'),
    (r'^reannotate/$', 'random_reannotate'),
    (r'^reannotated/$', 'reannotated'),
    
    (r'^skipped/$', 'skipped_sequences'),
    (r'^skipped/(?P<id>\d+)/delete/$', 'delete_skipped_sequence'),
    (r'^skipped/(?P<id>\d+)/$', 'edit_skipped_sequence'),
    (r'^skipped/add/$', 'add_skipped_sequence'),
)
